In [1]:
import numpy as np
import pandas as pd
import os.path
from sklearn.metrics import roc_auc_score

# Santander Customer Transaction Prediction (KAGGLE)

Leer de que trata la competencia

https://www.kaggle.com/c/santander-customer-transaction-prediction/overview

# Bajada de Dataset
La siguiente celda baja el dataset y lo guarda en la carpeta /data.

Luego de ejecutarla debería tener los archivos train.csv y test.csv en esta carpeta

In [2]:
if not os.path.isdir('data'):
    os.mkdir('data')
if not os.path.isfile('data/train.csv'):
    ! wget https://github.com/lab-pep-itba/santander-kaggle/blob/master/train.csv?raw=true
    ! mv train.csv\?raw\=true data/train.csv
if not os.path.isfile('data/test.csv'):
    ! wget https://github.com/lab-pep-itba/santander-kaggle/blob/master/test.csv?raw=true
    ! mv test.csv\?raw\=true data/test.csv

# Importar datos de test y de train

In [3]:
df_train = pd.read_csv('data/train.csv')

# TODO: Importar datos de test y asignarlos a la variable df_test desde la carpeta data/
# df_test  = 

In [4]:
# Miramos las primeras 5 observaciones del dataset
df_train.head()

ID_code  target    var_0   var_1    var_2   var_3    var_4   var_5   var_6  \
0  train_0       0   8.9255 -6.7863  11.9081  5.0930  11.4607 -9.2834  5.1187   
1  train_1       0  11.5006 -4.1473  13.8588  5.3890  12.3622  7.0433  5.6208   
2  train_2       0   8.6093 -2.7457  12.0805  7.8928  10.5825 -9.0837  6.9427   
3  train_3       0  11.0604 -2.1518   8.9522  7.1957  12.5846 -1.8361  5.8428   
4  train_4       0   9.8369 -1.4834  12.8746  6.6375  12.2772  2.4486  5.9405   

     var_7  ...  var_190  var_191  var_192  var_193  var_194  var_195  \
0  18.6266  ...   4.4354   3.9642   3.1364   1.6910  18.5227  -2.3978   
1  16.5338  ...   7.6421   7.7214   2.5837  10.9516  15.4305   2.0339   
2  14.6155  ...   2.9057   9.7905   1.6704   1.6858  21.6042   3.1417   
3  14.9250  ...   4.4666   4.7433   0.7178   1.4214  23.0347  -1.2706   
4  19.2514  ...  -1.4905   9.5214  -0.1508   9.1942  13.2876  -1.5121   

   var_196  var_197  var_198  var_199  
0   7.8784   8.5635  12.7803  -1.0914  
1   8.1267   8.7889  18.3560   1.9518  
2  -6.5213   8.2675  14.7222   0.3965  
3  -2.9275  10.2922  17.9697  -8.9996  
4   3.9267   9.5031  17.9974  -8.8104  

[5 rows x 202 columns]

In [5]:
df_train.columns

Index(['ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4',
       'var_5', 'var_6', 'var_7',
       ...
       'var_190', 'var_191', 'var_192', 'var_193', 'var_194', 'var_195',
       'var_196', 'var_197', 'var_198', 'var_199'],
      dtype='object', length=202)

Cuantas features (covariables, variable explicativa, variable independiente, variables exógenas) hay (dimensión de las observaciones, regresoras)? Que columna contiene la salida (variable dependiente, variable endógena)? Cuantas clases hay? Cuantas observaciones tiene train?

In [6]:
df_train.describe()

target          var_0          var_1          var_2  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        0.100490      10.679914      -1.627622      10.715192   
std         0.300653       3.040051       4.050044       2.640894   
min         0.000000       0.408400     -15.043400       2.117100   
25%         0.000000       8.453850      -4.740025       8.722475   
50%         0.000000      10.524750      -1.608050      10.580000   
75%         0.000000      12.758200       1.358625      12.516700   
max         1.000000      20.315000      10.376800      19.353000   

               var_3          var_4          var_5          var_6  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        6.796529      11.078333      -5.065317       5.408949   
std         2.043319       1.623150       7.863267       0.866607   
min        -0.040200       5.074800     -32.562600       2.347300   
25%         5.254075       9.883175     -11.200350       4.767700   
50%         6.825000      11.108250      -4.833150       5.385100   
75%         8.324100      12.261125       0.924800       6.003000   
max        13.188300      16.671400      17.251600       8.447700   

               var_7          var_8  ...        var_190        var_191  \
count  200000.000000  200000.000000  ...  200000.000000  200000.000000   
mean       16.545850       0.284162  ...       3.234440       7.438408   
std         3.418076       3.332634  ...       4.559922       3.023272   
min         5.349700     -10.505500  ...     -14.093300      -2.691700   
25%        13.943800      -2.317800  ...      -0.058825       5.157400   
50%        16.456800       0.393700  ...       3.203600       7.347750   
75%        19.102900       2.937900  ...       6.406200       9.512525   
max        27.691800      10.151300  ...      18.440900      16.716500   

             var_192        var_193        var_194        var_195  \
count  200000.000000  200000.000000  200000.000000  200000.000000   
mean        1.927839       3.331774      17.993784      -0.142088   
std         1.478423       3.992030       3.135162       1.429372   
min        -3.814500     -11.783400       8.694400      -5.261000   
25%         0.889775       0.584600      15.629800      -1.170700   
50%         1.901300       3.396350      17.957950      -0.172700   
75%         2.949500       6.205800      20.396525       0.829600   
max         8.402400      18.281800      27.928800       4.272900   

             var_196        var_197        var_198        var_199  
count  200000.000000  200000.000000  200000.000000  200000.000000  
mean        2.303335       8.908158      15.870720      -3.326537  
std         5.454369       0.921625       3.010945      10.438015  
min       -14.209600       5.960600       6.299300     -38.852800  
25%        -1.946925       8.252800      13.829700     -11.208475  
50%         2.408900       8.888200      15.934050      -2.819550  
75%         6.556725       9.593300      18.064725       4.836800  
max        18.321500      12.000400      26.079100      28.500700  

[8 rows x 201 columns]

In [7]:
# TODO: Inspeccionar test
# Puede ejecutar los métodos que crea necesarios. Recomendamos describe, columns, shape, head

Que columna esta en los datos de train pero no en los de test? Cuantas observaciones de test hay?

In [8]:
df_train['target'].value_counts()

0    179902
1     20098
Name: target, dtype: int64

Que proporción de valores de 0s hay?

In [9]:
179902/(179902+20098)

0.89951

# Train, Val, Test

In [10]:
X_train = df_train.drop(columns=['ID_code', 'target']).values[:160_000]
X_val = df_train.drop(columns=['ID_code', 'target']).values[160_000:]
y_train = df_train['target'].values[:160_000]
y_val = df_train['target'].values[160_000:]

In [11]:
from sklearn.linear_model import LogisticRegression

In [12]:
model = LogisticRegression(solver='lbfgs')

In [13]:
%time model.fit(X_train, y_train)

CPU times: user 8.77 s, sys: 152 ms, total: 8.92 s
Wall time: 4.84 s


/Users/julianganzabal/anaconda3/envs/mllab/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:758: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='lbfgs',
          tol=0.0001, verbose=0, warm_start=False)

A que se debe el warning termino de converger?

In [14]:
print(roc_auc_score(y_train, model.predict_proba(X_train)[:,1]))
print(model.score(X_train, y_train))

0.8507527588341866
0.91206875


In [15]:
print(roc_auc_score(y_val, model.predict_proba(X_val)[:,1]))
print(model.score(X_val, y_val))

0.8527383932243496
0.912275


cuantos parámetros aprendio el modelo?

# Normalizar los datos

In [19]:
means = X_train.mean(axis=0)
stds = X_train.std(axis=0)

In [20]:
X_train_normalized = (X_train - means)/stds
X_val_normalized = (X_val - means)/stds

In [21]:
model_2 = LogisticRegression(solver='lbfgs', C=1e12)
%time model_2.fit(X_train_normalized, y_train)

CPU times: user 979 ms, sys: 110 ms, total: 1.09 s
Wall time: 731 ms


LogisticRegression(C=1000000000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
          solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

In [22]:
print(model_2.score(X_train_normalized, y_train))
print(roc_auc_score(y_train, model_2.predict_proba(X_train_normalized)[:,1]))

0.9144
0.8606427374799213


In [23]:
print(model_2.score(X_val_normalized, y_val))
print(roc_auc_score(y_val, model_2.predict_proba(X_val_normalized)[:,1]))

0.914525
0.8629073823960288


In [24]:
np.argsort(np.abs(model_2.coef_))[0][::-1]

array([ 81, 139,   6,  12,  53, 110,  76,  99, 146, 174,  26,  21,  22,
        80, 190, 166, 165, 198,  13,  34, 169,  44,   2, 148,   0,  40,
       133, 179, 170,  78,  94,   1, 184, 109,  33, 115,  92,  67, 149,
       108, 191, 122, 173, 154,  18,  86, 192, 118, 107, 121, 147,  95,
         9,  75,  35, 164, 177, 197, 172,  36, 127,  89, 123, 155,  91,
       188,  56,  87,  71,  48,   5,  93, 162, 106, 157, 130, 141, 145,
        24, 151,  32, 167, 163, 150, 186, 119,  49,  31, 180,  23, 111,
       195,  90, 131, 125, 137, 114, 199,  43, 116, 135,  52,  58, 128,
        70, 104, 175, 112, 132, 105,  11, 196,  85,  82, 194,  51,  28,
       142,  83,  66, 134, 144, 138,  74,  45, 156,  77,  55,  97, 140,
        20,  54, 193,  57,  88, 178,   8, 102, 113,  62,  15, 143, 159,
       187, 181, 171,  63,  72,  64,  50,  59, 120, 168, 182, 101,  25,
        68,   3,  65, 152,   4,  84,  37,  42, 176,  61, 129,  19, 189,
        69,  47,  60,  16,  27,  29,  79,  73, 158,  96, 160,  4

In [25]:
correlations = []
for i in range(200):
    correlations.append(np.corrcoef(y_train, X_train_normalized[:,i])[1,0])

In [26]:
np.argsort(np.abs(correlations))[::-1]

array([ 81, 139,  12, 110,   6,  26,  53, 146, 174,  76,  99,  80, 166,
        22, 165,  21, 190, 148,   2,  13,  34, 133,   0, 198, 169, 109,
       179,  44,  40,   1, 115, 149, 170, 184,  78,  94,  92, 108,  67,
       191,  33,  18, 154, 173,  86, 122, 192, 147, 118,   9, 121,  75,
        95, 164, 123,  35,  91,  36, 172, 127, 107, 155,  89, 177, 197,
        56,  93, 188,  87,  71, 162,  48, 157, 106, 141, 145,   5,  32,
       163, 131, 167, 186, 119,  49,  24, 151, 130,  90, 111, 135, 180,
       125,  43,  51, 114, 195, 199,  52,  23, 150,  31, 116,  85,  70,
       137, 105, 128, 104,  58, 112, 196, 132,  11,  28, 175,  66,  82,
       194, 156,  83, 142,  45, 144,  88,  74, 178, 138,  77,   8,  97,
       134,  20,  55, 193,  54,  15, 102,  57, 159, 140, 171,  62, 113,
       187,  63, 143,  64,  25, 181,  50, 120, 168,  59,   3,  72,  65,
        68,  84, 101,  19,   4,  37,  61,  69, 189, 152, 182,  42,  16,
       129, 176,  47,  79, 153,  14, 183,  46, 160,  73,  60,  9

# Feature engineering

In [73]:
X_train_sq = X_train_normalized**2
means_sq = X_train_sq.mean(axis=0)
stds_sq = X_train_sq.std(axis=0)
X_val_sq = X_val_normalized**2
X_train_FE = np.append(X_train_normalized, (X_train_sq - means_sq)/stds_sq, axis=1)
X_val_FE = np.append(X_val_normalized, (X_val_normalized**2-means_sq)/stds_sq, axis=1)

In [74]:
model_3 = LogisticRegression(solver='lbfgs', C=1e12, max_iter=1000)
%time model_3.fit(X_train_FE, y_train)

CPU times: user 2.39 s, sys: 602 ms, total: 2.99 s
Wall time: 2.31 s


LogisticRegression(C=1000000000000.0, class_weight=None, dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=1000,
          multi_class='warn', n_jobs=None, penalty='l2', random_state=None,
          solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)

In [75]:
print(model_3.score(X_train_FE, y_train))
print(roc_auc_score(y_train, model_3.predict_proba(X_train_FE)[:,1]))

0.9218625
0.8910807733829336


In [76]:
print(model_3.score(X_val_FE, y_val))
print(roc_auc_score(y_val, model_3.predict_proba(X_val_FE)[:,1]))

0.9221
0.8927208344053872


In [77]:
np.argsort(np.abs(model_3.coef_))[0][::-1]

array([139,  81,   6,  53,  12,  21,  76, 174, 110,  34, 146,  26, 169,
        99, 165, 281,  22, 166, 190,  78,  33,  40,  13, 170, 149,  80,
       148, 184,  94, 109, 133, 192,  92, 122, 115,  67, 121, 198,   0,
         1, 173, 179,   2, 212,  18, 118, 108, 253, 398, 107, 191, 172,
       177,  44, 154, 310, 164,  35, 197, 226, 188,  36, 339, 299,  75,
       147, 244,   9, 280,  86,  87, 366,  95,  89,  48, 390, 127,  91,
       222, 309,  71, 346, 155, 202,   5, 323, 374, 379,  56, 145, 106,
       162, 123, 206, 221,  32, 186, 141, 200, 150, 348, 151,  31, 365,
       199,  49, 130, 240,  23, 278, 167, 157,  24, 333,  90, 276,  93,
       111, 119, 354, 137, 364, 195, 286, 363, 128, 112, 180, 380,  52,
       104, 114,  58, 131,  70, 355, 116, 125, 135, 295, 370, 233, 391,
       292, 201,  43, 275, 175, 196, 293, 357, 388, 294,  85, 163, 213,
       347,  82, 308, 142, 132,  28, 105,  11, 319, 234, 194, 291,  74,
       205,  97,  77, 140, 315,  45, 322,  20, 369,  55, 267, 25

In [115]:
np.argsort(np.abs(model_3.coef_)*X_train_FE.std(axis=0))[0][::-1]

array([139,  81,   6,  53,  12,  21,  76, 174, 110,  34, 146,  26, 169,
        99, 165, 281,  22, 166, 190,  78,  33,  40,  13, 170, 149,  80,
       148, 184,  94, 109, 133, 192,  92, 115, 122,  67, 121, 198,   0,
         1, 173, 179,   2, 212,  18, 118, 108, 253, 107, 398, 191, 172,
       177,  44, 154, 310, 164,  35, 197, 226, 188,  36, 339, 299,  75,
       147, 244,   9, 280,  86,  87, 366,  95,  89,  48, 127, 390,  91,
       222, 309,  71, 346, 155, 202,   5, 323, 374, 379,  56, 145, 106,
       162, 123, 206, 221,  32, 186, 141, 200, 150, 348, 151,  31, 365,
        49, 199, 130, 240,  23, 167, 278, 157,  24, 333,  90, 276, 111,
        93, 119, 354, 137, 364, 195, 286, 363, 128, 112, 180, 380,  52,
       104, 114, 131,  58,  70, 355, 116, 125, 135, 295, 370, 233, 391,
       292, 201,  43, 275, 196, 175, 293, 357, 388, 294, 163,  85, 213,
       347,  82, 308, 142, 132,  28, 105,  11, 319, 234, 194, 291,  74,
       205,  97,  77, 140,  45, 315, 322,  20, 369,  55, 267, 25